### ISSUE TITLE
Use a different file extension for C++-only headers

### ISSUE THREAD

**Issue by DaoWen** [habanero-rice/hclib#10]
Right now it's not possible to tell which headers are C-compatible without actually looking at the code. While this probably isn't much of a problem for the end user, I think it's a problem from a maintenance perspective.

For example, if I want to `git grep` for something, and I'm only interested in C++ results, it's much harder to sift through the output. (The same is true if I'm only interested in the C code.)

I suggest using `.hpp` like Boost, but really I'm fine with anything as long as we can differentiate between the C-compatible and C++-only headers.

**Comment by agrippa** [comment]
.hpp sounds good to me as well.
