### ISSUE TITLE
Remove HC_MALLOC and HC_FREE macros

### ISSUE THREAD

**Issue by DaoWen** [habanero-rice/hclib#11]
These macros are an artifact from when we had a version of the Cilk allocator built in the HC runtime for the HC language. We've never had that code as part of HClib, since we now prefer directly linking (or using `LD_PRELOAD`) with third-party scalable allocators like TBB's.

This should be a simple matter of find/replace with `malloc`/`free` in the C code. The C++ code shouldn't be calling these C functions, so we'd replace with `new`/`delete` instead.

**Comment by vkaries** [comment]
Yes, we can get rid of this. Also, .hpp sounds good to me as well.
