### ISSUE TITLE
Wrong number of places mentioned in the hpt0.xml

### ISSUE THREAD

**Issue by naman** [habanero-rice/hclib#30]
The ![hpt0.xml](https://github.com/habanero-rice/hclib/edit/master/test/hpt/hpt0.xml#L6) says 
`<place num="3" type="cache"> <!-- 2 places with common L3 in each -->` but it should actually be 
`<place num="2" type="cache"> <!-- 2 places with common L3 in each -->`.

**Comment by naman** [comment]
#31

**Comment by agrippa** [comment]
Thanks @naman !
