### ISSUE TITLE
Missing HC_CUDA Makro

### ISSUE THREAD

**Issue by NecOnIce** [habanero-rice/hclib#4]
The Function:
place_t **get_nvgpu_places(int *n_nvgpu_places);

is not excluded with an ifdef for HC_CUDA, so it is not possible to use the HabaneroUPC++ Library without the Cuda Feature.

**Comment by agrippa** [comment]
Thank you for pointing that out, the following commit should address this issue (but please let us know if you still have problems):

https://github.com/habanero-rice/hcpp/commit/99fd1f25341721e542979201fc41cb8b9ce921d2
