### ISSUE TITLE
Finish Statement never finishes

### ISSUE THREAD

**Issue by NecOnIce** [habanero-rice/hclib#5]
I have tried to write and run a simple Program which only prints "Hello World" on each Place / Worker but the Program doesn't terminates. I've tried several combinations of async's but none has worked and the finish statement never finishes ... here is my sample Program:

```
#define GASNET_PAR

#include "hcupc_spmd.h"
#include "hclib.h"
#include "hclib-place.h"
#include <iostream>

using namespace std;

int main(int argc, char **argv) {

    hupcpp::launch(&argc, &argv, [] () {

        hclib::finish([] () {

            int numWorkers = hclib::num_workers();
            cout << "Total Workers: " << numWorkers << endl;

            int numPlaces = hclib::get_num_places(place_type_t::CACHE_PLACE);
            place_t **cachePlaces = (place_t**) malloc(sizeof(place_t*) * numPlaces);
            hclib::get_places(cachePlaces, place_type_t::CACHE_PLACE);

            for (int i = 0; i < numPlaces; i++) {

                place_t *currentPlace = cachePlaces[i];
                if (currentPlace->nChildren != 0) {
                    cout << "CachePlace with children found, skipping" << endl;
                    continue;
                }

                hclib::async([=] () {
                    cout << "Hello I'm Worker " << hclib::current_worker() << " of " << numWorkers << "Workers" << endl;
                });
            }


            free(cachePlaces);

        });
    });

    return 0;
}
```

and here is my hpt.xml:

```
<?xml version="1.0"?>
<!DOCTYPE HPT SYSTEM "hpt.dtd">

<HPT version="0.1" info="an HPT for Testing, 2 dual core processors">
    <place num="1" type="mem" >
        <place num="1" type="cache" >
            <worker num="1" />
        </place>
        <place num="1" type="cache" >
            <worker num="1" />
        </place>
    </place>
</HPT>
```

Additionally there is only the Worker number 0 which is running the async's.
It would be very nice, if you can help me out with this Problem :)

**Comment by agrippa** [comment]
@NecOnIce Are you trying to run a distributed memory program using Habanero-UPC, or a shared memory multi-threaded program only using HClib? I noticed that you used hupcpp::launch and GASNET_PAR which are more parts of Habanero-UPC than HClib, but the rest of the application looks like it is only targeting a shared memory system. We'll need to verify that the actual problem is in HClib (the repo this bug is filed in), otherwise we should get this moved over to the Habanero-UPC repo at [1].

Could you see if the following code runs and finishes on your system?

```
#include "hclib_cpp.h"
#include "hclib-place.h"
#include <iostream>

using namespace std;

int main(int argc, char **argv) {

    hclib::launch(&argc, argv, [] () {

            hclib::finish([] () {

                int numWorkers = hclib::num_workers();
                cout << "Total Workers: " << numWorkers << endl;

                int numPlaces = hclib::get_num_places(place_type_t::CACHE_PLACE);
                place_t **cachePlaces = (place_t**) malloc(sizeof(place_t*) * numPlaces);
                hclib::get_places(cachePlaces, place_type_t::CACHE_PLACE);

                for (int i = 0; i < numPlaces; i++) {

                place_t *currentPlace = cachePlaces[i];
                if (currentPlace->nChildren != 0) {
                cout << "CachePlace with children found, skipping" << endl;
                continue;
                }   

                hclib::async([=] () {
                    cout << "Hello I'm Worker " << hclib::current_worker() << " of " << numWorkers << "Workers" << endl;
                    }); 
                }   


                free(cachePlaces);

            }); 
    }); 

    return 0;
}
```

That program is nearly identical to your original one and uses only HClib, not any Habanero-UPC. If that program works correctly, then we'll need to move this bug to Habanero-UPC as it would seem to be an issue for Habanero-UPC and not HClib. I've verified that the above code compiles and runs on one of my machines.

[1] https://github.com/habanero-rice/habanero-upc

**Comment by NecOnIce** [comment]
I will try to compile and run your program tomorrow. I'm living in Germany and here it is 0:45 O'Clock :D.

Today i have run my program with a different hpt file:

```
<?xml version="1.0"?>
<!DOCTYPE HPT SYSTEM "hpt.dtd">

<HPT version="0.1" info="an HPT for Testing, 2 dual core processors">
    <place num="1" type="mem" >
        <place num="1" type="cache" >
            <worker num="2" />
        </place>
        <place num="1" type="cache" >
            <worker num="2" />
        </place>
    </place>
</HPT>
```

With this hpt File it has worked...

My Intention was to write an program with HabaneroUPC++ for a Single machine. In this case my Notebook, just for testing. It is possible to run only a multithreaded program on one machine with HabaneroUPC++ ? Additionally i find it interesting to know, if it is possible to use the hclip functions for HPT in a HabaneroUPC++ program ?

Greetings
NecOnIce

**Comment by agrippa** [comment]
That's interesting that changing from 1 worker per place to 2 seems to have fixed the issue, I will need to look into that. It would suggest this is an HClib issue after all.

Yes, you can run a single-machine multithreaded program with HabaneroUPC++. That is definitely supported.

And you should also be able to use the HPT functions from a HabaneroUPC++ program.

**Comment by agrippa** [comment]
Hmm, unfortunately I tried running with your first HPT file and wasn't able to reproduce the hangs that you were experiencing with that setup when using the HClib program that I provided. It's possible this is an issue unique to Habanero-UPC++ because it dedicates a thread to handling communication. Tomorrow, if you are unable to reproduce the issue using the HClib-only program I've provided and the first HPT file you used, we'll move this to the Habanero-UPC++ repo and start looking at it from that angle.

**Comment by NecOnIce** [comment]
I have tried to run your program but i get a SegmentationFault at hclib-runtime.c at line 456

```
    if (promise_list) {
        check_if_hcupc_distributed_promises(promise_list); // <- SegmentationFault
    }
```

**Comment by agrippa** [comment]
That's caused by the fact that your HClib was built to support Habanero-UPC++, but we aren't currently running under the Habanero-UPC++ runtime. If you run install.sh from the hcpp/ root directory and then recompile the application code, this SEGFAULT should go away.

**Comment by NecOnIce** [comment]
I have now found another strange behaviour ... when i'm running a program with a finish or finish_spmd Lambda, this Lambda is executed twice! At the moment i haven't tried to recompile the HClib, but i will do in the next hours. For that i checkout a new copy from HClib to have both Versions...

**Comment by NecOnIce** [comment]
If you have already read what i have written yesterday, you can forget it, the error was inside my own Program. Sorry for that ...

**Comment by NecOnIce** [comment]
I have now compiled the HClib only version and has run the Program you have provided, but the Problem stays nearly the same. The Program starts up and shuts down now, but if i use my first hpt file with just one worker per Place, the content of the finish Lambda is never executed ... if i use the hpt file with two workers per Place, the program runs correctly.

**Comment by agrippa** [comment]
Hi @NecOnIce, sorry about the delay in replying. That's very odd. To make sure I understand everything, you're saying that with two places and one worker per place the program you pasted doesn't even get to the "Total Workers: " print statement? I'm having trouble reproducing on my side so I might need to try a couple of other systems. Could you provide your machine configuration? e.g. hardware, OS version, gcc version.

**Comment by NecOnIce** [comment]
Yes this is right, the total Workers aren't printed. My Machine:

CPU: Intel Core i5 M 520  @ 2.40GHz, 2395 MHz, 2 Cores, 4 logic Cores
OS: Ubuntu 14.04 LTS
GCC: 4.8

Dell Vostro 3500 with extendend Memory to 6GB and an SSD Harddrive.

And i have excluded the TBB_MALLOC Lib while building hclib.

**Comment by vkaries** [comment]
If I understand correctly, you are unable to run the finish lambda when you use only one worker, but you are able to execute it with more than one worker (per place?).

To me this sounds like the triggering of communication worker (worker-id=0). If you are using only hclib, then you do a clean build (./clobber.sh) and simply use ./install.sh script. If you are using HabaneroUPC++, then you have to use more than one worker/place, without which it won’t work. The communication worker does not do anything other than communication. It will push any async task inside a finish block onto its deque and wait for the computation worker to steal. Fore more info, please look the the PGAS14 paper on HabaneroUPC++ (http://nic.uoregon.edu/pgas14/papers/pgas14_submission_11.pdf http://nic.uoregon.edu/pgas14/papers/pgas14_submission_11.pdf)

Hope this helps.

Thanks
Vivek Kumar

**Comment by vkaries** [comment]
Also, can you please give the output of the command “env” before you build the hclib/habanero-upc library and also before you run the executable?

Thanks
Vivek

**Comment by agrippa** [comment]
@NecOnIce was this ever resolved?

**Comment by NecOnIce** [comment]
Hi,
sorry for the very late response. The behaviour seems to be correct, for hupcpp i need at least 2 workers per place. So this is closed.

Thanks
NecOnIce
